export * from "./Landing";
export * from "./MovieDetails";
export * from "./Movies";
export * from "./Register";
export * from "./Login";
export * from "./admin/AdminLogin";
export * from "./admin/AdminMovies";
export * from "./admin/AdminAddMovie";
export * from "./admin/AdminMovieDetails";
